# Generated by Django 5.2.8 on 2026-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0002_scanrequest_scannedlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedlot',
            name='estimated_resale_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='estimated_resale_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
