# Generated by Django 5.2.8 on 2026-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0003_scannedlot_estimated_resale_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrequest',
            name='max_pages',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
