# Generated by Django 5.2.8 on 2026-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0004_scanrequest_max_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedlot',
            name='max_hammer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
