# Generated by Django 5.2.8 on 2026-09-17 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0005_scannedlot_max_hammer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('max_pages', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('lots_harvested', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('auctioneer_name', models.CharField(blank=True, max_length=255)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_bid_count', models.IntegerField(blank=True, null=True)),
                ('auction_close_datetime', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('lot_url', models.URLField(blank=True)),
                ('harvested_at', models.DateTimeField(auto_now_add=True)),
                ('harvest_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='albright_reselling_app.harvestrequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-harvested_at'],
                'indexes': [models.Index(fields=['category'], name='albright_re_categor_06a2fd_idx'), models.Index(fields=['auctioneer_name'], name='albright_re_auction_8d9e22_idx')],
            },
        ),
    ]
