# Generated by Django 5.2.8 on 2026-09-17 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0006_harvestrequest_historicallot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedlot',
            name='actual_price_realized',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='auction_close_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='auctioneer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='final_bid_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeepDiveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('resale_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resale_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_hammer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence', models.CharField(blank=True, max_length=10)),
                ('analysis', models.TextField(blank=True)),
                ('images_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dives', to='albright_reselling_app.scannedlot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dive_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_requests', to=settings.AUTH_USER_MODEL)),
                ('scan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_requests', to='albright_reselling_app.scanrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
