# Generated by Django 5.2.8 on 2026-09-17 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0007_scannedlot_actual_price_realized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='analysis_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='estimated_resale_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='estimated_resale_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('auctioneer_name', models.CharField(blank=True, max_length=255)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('min_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_lots', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('lots_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicallot',
            name='last_analysis_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_lots', to='albright_reselling_app.analysisrequest'),
        ),
    ]
