# Generated by Django 5.2.8 on 2026-09-18 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0008_historicallot_analysis_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedlot',
            name='discount_likelihood_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scannedlot',
            name='discount_likelihood_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrequest',
            name='reference_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_scored_against', to='albright_reselling_app.analysisrequest'),
        ),
    ]
