# Generated by Django 5.2.8 on 2026-09-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0009_scannedlot_discount_likelihood_reasoning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bid_count', models.IntegerField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('matched_keyword', models.CharField(blank=True, max_length=100)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['end_time'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='LotEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='coins', max_length=30)),
                ('method', models.CharField(default='regex', max_length=10)),
                ('coin_keys', models.CharField(blank=True, max_length=200)),
                ('silver_oz', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gold_oz', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('confidence', models.CharField(default='low', max_length=10)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('excluded_reason', models.CharField(blank=True, max_length=200)),
                ('melt_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_bid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('headroom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_candidate', models.BooleanField(default=False)),
                ('llm_title_hash', models.CharField(blank=True, max_length=64)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='albright_reselling_app.sourcedlot')),
            ],
            options={
                'ordering': ['-is_candidate', '-headroom'],
            },
        ),
    ]
