# Generated by Django 5.2.8 on 2026-09-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0010_spotprice_sourcedlot_lotevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lots_seen', models.IntegerField(default=0)),
                ('candidates', models.IntegerField(default=0)),
                ('llm_calls', models.IntegerField(default=0)),
                ('failed_keywords', models.JSONField(blank=True, default=list)),
                ('stopped_early', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
