# Generated by Django 5.2.8 on 2026-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0011_scanrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotevaluation',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotevaluation',
            name='lead_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='leads',
            field=models.IntegerField(default=0),
        ),
    ]
