# Generated by Django 5.2.8 on 2026-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0012_lotevaluation_is_lead_lotevaluation_lead_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedlot',
            name='final_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedlot',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sourcedlot',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
