# Generated by Django 5.2.8 on 2026-09-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0013_sourcedlot_final_checked_at_sourcedlot_final_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('done', 'Done'), ('error', 'Error')], default='done', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('resale_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resale_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_max_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence', models.CharField(blank=True, max_length=10)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='albright_reselling_app.sourcedlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
