# Generated by Django 5.2.8 on 2026-09-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0014_aireview'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireview',
            name='bid_at_review',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aireview',
            name='lot_end_time_at_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireview',
            name='melt_at_review',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aireview',
            name='scanner_max_bid_at_review',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
