# Generated by Django 5.2.8 on 2026-10-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0015_aireview_bid_at_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedlot',
            name='bid_count_at_close',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedlot',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sourcedlot',
            name='first_seen_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
