# Generated by Django 5.2.8 on 2026-10-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0016_sourcedlot_bid_count_at_close_sourcedlot_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('candidate', 'Candidate'), ('lead', 'Lead'), ('check_by_hand', 'Check by Hand')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='albright_reselling_app.sourcedlot')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('lot', 'kind')},
            },
        ),
    ]
