# Generated by Django 5.2.8 on 2026-10-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0017_alertsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='ai_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='albright_reselling_app.aireview'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ai_suggested_max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='buy_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='buyer_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='inbound_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='listing_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='melt_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='predicted_sale_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='predicted_sale_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='predicted_sale_source',
            field=models.CharField(blank=True, choices=[('scanner', 'Scanner'), ('ai_review', 'AI Review')], max_length=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='purchase_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sales_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='scanner_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='albright_reselling_app.sourcedlot'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='scanner_max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sell_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sell_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='status',
            field=models.CharField(choices=[('holding', 'Holding'), ('partially_sold', 'Partially Sold'), ('sold_out', 'Sold Out'), ('written_off', 'Written Off')], default='holding', max_length=20),
        ),
        migrations.CreateModel(
            name='LedgerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('channel', models.CharField(choices=[('ebay', 'eBay'), ('scrap_gold', 'Scrap/Gold Buyer'), ('local_facebook', 'Local/Facebook'), ('etsy', 'Etsy'), ('other', 'Other')], default='other', max_length=20)),
                ('selling_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outbound_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='albright_reselling_app.ledgerentry')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
