# Generated by Django 5.2.8 on 2026-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0019_backfill_ledgerentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalAlertSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('alert_type', models.CharField(choices=[('blocked', 'Blocked'), ('zero_lots', 'Zero Lots'), ('stale', 'Stale')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
