# Generated by Django 5.2.8 on 2026-10-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0020_criticalalertsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_max_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('likely_won', 'Likely Won'), ('lost', 'Lost'), ('unknown', 'Unknown')], default='watching', max_length=20)),
                ('closing_alert_sent', models.BooleanField(default=False)),
                ('result_alert_sent', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_watch', to='albright_reselling_app.sourcedlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
