# Generated by Django 5.2.8 on 2026-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0021_bidwatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsent',
            name='kind',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('lead', 'Lead'), ('check_by_hand', 'Check by Hand'), ('zero_bid', 'Zero Bid'), ('relisted', 'Relisted')], max_length=20),
        ),
    ]
