# Generated by Django 5.2.8 on 2026-10-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_reselling_app', '0023_calibrationsuggestion_calibrationoverride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('inputs', models.JSONField(default=dict)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanner_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_calculations', to='albright_reselling_app.sourcedlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
