# Generated by Django 5.2.8 on 2025-12-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('expected_retirement_date', models.DateField()),
                ('risk_tolerance', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('dependents_count', models.IntegerField()),
                ('home_street_address', models.CharField(max_length=150)),
                ('home_state', models.CharField(max_length=50)),
                ('home_city', models.CharField(max_length=50)),
                ('home_zip', models.CharField(max_length=50)),
                ('employment_status', models.CharField(max_length=50)),
                ('goal_type', models.CharField(max_length=50)),
                ('maximum_tolerable_drawdown', models.FloatField()),
                ('monthly_contribution_amount', models.FloatField()),
                ('liquid_assets', models.FloatField()),
                ('debt', models.FloatField()),
            ],
        ),
    ]
