# Generated by Django 5.2.8 on 2026-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0002_investorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditSentimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('mentions_24h', models.PositiveIntegerField(default=0)),
                ('positive_24h', models.PositiveIntegerField(default=0)),
                ('neutral_24h', models.PositiveIntegerField(default=0)),
                ('negative_24h', models.PositiveIntegerField(default=0)),
                ('mentions_7d', models.PositiveIntegerField(default=0)),
                ('positive_7d', models.PositiveIntegerField(default=0)),
                ('neutral_7d', models.PositiveIntegerField(default=0)),
                ('negative_7d', models.PositiveIntegerField(default=0)),
                ('mentions_30d', models.PositiveIntegerField(default=0)),
                ('positive_30d', models.PositiveIntegerField(default=0)),
                ('neutral_30d', models.PositiveIntegerField(default=0)),
                ('negative_30d', models.PositiveIntegerField(default=0)),
                ('positive_change_24h_vs_7d_avg', models.FloatField(blank=True, null=True)),
                ('negative_change_24h_vs_7d_avg', models.FloatField(blank=True, null=True)),
                ('positive_change_7d_vs_30d_avg', models.FloatField(blank=True, null=True)),
                ('negative_change_7d_vs_30d_avg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-mentions_24h'],
            },
        ),
        migrations.CreateModel(
            name='RedditDailyMentionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='albright_tr_symbol_dd9d25_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='unique_symbol_per_day')],
            },
        ),
    ]
