# Generated by Django 5.2.8 on 2026-08-22 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0003_redditsentimentsummary_redditdailymentioncount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlpacaCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField()),
                ('encrypted_secret_key', models.TextField()),
                ('is_paper', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alpaca_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
