# Generated by Django 5.2.8 on 2026-08-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0004_alpacacredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('strategy_type', models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('symbols', models.CharField(help_text='Comma-separated symbols this strategy trades, e.g. AAPL,MSFT,NVDA', max_length=500)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Strategy-specific config, e.g. {"short_period": 10, "long_period": 30}')),
                ('position_size', models.PositiveIntegerField(default=1, help_text='Shares per trade')),
                ('is_active', models.BooleanField(default=False)),
                ('is_paper', models.BooleanField(default=True, help_text='Always True for now — live trading will be a separate, deliberate switch later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('side', models.CharField(max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('realized_pnl', models.FloatField(blank=True, null=True)),
                ('alpaca_order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='albright_trading_app.strategy')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
    ]
