# Generated by Django 5.2.8 on 2026-08-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0005_strategy_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='is_paper',
            field=models.BooleanField(default=True, help_text="Always True for now. The engine also independently checks the owner's connected Alpaca account and refuses to execute if that account isn't paper — this flag alone isn't the only guard."),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_strategy_name_per_user'),
        ),
    ]
