# Generated by Django 5.2.8 on 2026-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0006_strategy_user_alter_strategy_is_paper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='position_size',
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_max_day_change_pct',
            field=models.FloatField(blank=True, help_text='Only include stocks up at most this % today', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_day_change_pct',
            field=models.FloatField(blank=True, help_text='Only include stocks up at least this % today', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_reddit_mentions_24h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_reddit_positive_ratio',
            field=models.FloatField(blank=True, help_text="0.0–1.0 — require at least this fraction of today's Reddit mentions to be positive", null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_sectors',
            field=models.CharField(blank=True, help_text='Comma-separated GICS sectors to include. Leave blank for all sectors.', max_length=500),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_hold_days',
            field=models.PositiveIntegerField(blank=True, help_text='Force-close after this many days regardless of signal', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='position_sizing_method',
            field=models.CharField(choices=[('fixed_shares', 'Fixed number of shares'), ('fixed_dollar', 'Fixed dollar amount'), ('pct_buying_power', '% of buying power')], default='fixed_shares', max_length=20),
        ),
        migrations.AddField(
            model_name='strategy',
            name='position_sizing_value',
            field=models.FloatField(default=1, help_text='Meaning depends on method: share count, dollar amount, or percent (e.g. 5 = 5%)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stop_loss_pct',
            field=models.FloatField(blank=True, help_text='Close once down this %', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='take_profit_pct',
            field=models.FloatField(blank=True, help_text='Close once up this %', null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='is_paper',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='symbols',
            field=models.CharField(blank=True, help_text='Optional manual override — comma-separated symbols. Leave blank to use filters instead.', max_length=500),
        ),
    ]
