# Generated by Django 5.2.8 on 2026-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0007_remove_strategy_position_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='trailing_stop_pct',
            field=models.FloatField(blank=True, help_text='Close if price falls this % from its highest point since entry', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='peak_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='filter_max_day_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='filter_min_day_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='filter_min_reddit_positive_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='filter_sectors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Built automatically from the strategy-specific form fields — not edited directly.'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='position_sizing_method',
            field=models.CharField(choices=[('fixed_shares', 'Fixed number of shares'), ('fixed_dollar', 'Fixed dollar amount'), ('pct_buying_power', '% of buying power'), ('pct_cash', '% of cash')], default='fixed_shares', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='position_sizing_value',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover'), ('reddit_sentiment_threshold', 'Reddit Sentiment Threshold'), ('rsi_threshold', 'RSI Threshold'), ('bollinger_reversion', 'Bollinger Band Reversion'), ('price_breakout', 'Price Breakout')], max_length=50),
        ),
    ]
