# Generated by Django 5.2.8 on 2026-08-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0008_strategy_trailing_stop_pct_trade_peak_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='max_daily_entries_per_symbol',
            field=models.PositiveIntegerField(blank=True, help_text='Limit new entries into the same symbol per day. Leave blank for unlimited.', null=True),
        ),
    ]
