# Generated by Django 5.2.8 on 2026-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0009_strategy_max_daily_entries_per_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='filter_min_reddit_positive_vs_negative_ratio',
            field=models.FloatField(blank=True, help_text='Positive mentions as a fraction of (positive + negative) only — neutral mentions excluded entirely.', null=True),
        ),
    ]
