# Generated by Django 5.2.8 on 2026-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0010_strategy_filter_min_reddit_positive_vs_negative_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hidden from the main Strategies page but not deleted. Always inactive while archived.'),
        ),
    ]
