# Generated by Django 5.2.8 on 2026-08-28 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0011_strategy_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover'), ('reddit_sentiment_threshold', 'Reddit Sentiment Threshold'), ('rsi_threshold', 'RSI Threshold'), ('bollinger_reversion', 'Bollinger Band Reversion'), ('price_breakout', 'Price Breakout')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('symbols', models.CharField(blank=True, help_text='Optional manual override — comma-separated underlying symbols. Leave blank to use filters instead.', max_length=500)),
                ('filter_sectors', models.CharField(blank=True, max_length=500)),
                ('filter_min_price', models.FloatField(blank=True, null=True)),
                ('filter_max_price', models.FloatField(blank=True, null=True)),
                ('filter_min_day_change_pct', models.FloatField(blank=True, null=True)),
                ('filter_max_day_change_pct', models.FloatField(blank=True, null=True)),
                ('filter_min_reddit_mentions_24h', models.PositiveIntegerField(blank=True, null=True)),
                ('filter_min_reddit_positive_ratio', models.FloatField(blank=True, null=True)),
                ('filter_min_reddit_positive_vs_negative_ratio', models.FloatField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('option_strike_method', models.CharField(choices=[('atm', 'At-the-Money')], default='atm', max_length=20)),
                ('option_target_dte', models.PositiveIntegerField(choices=[(7, '7 days'), (30, '30 days'), (60, '60 days'), (90, '90 days'), (120, '120 days')], default=30, help_text='Target days-to-expiration when selecting a contract.')),
                ('position_sizing_method', models.CharField(choices=[('fixed_contracts', 'Fixed number of contracts'), ('fixed_dollar', 'Fixed dollar amount'), ('pct_buying_power', '% of buying power'), ('pct_cash', '% of cash')], default='fixed_contracts', max_length=20)),
                ('position_sizing_value', models.FloatField(default=1)),
                ('take_profit_pct', models.FloatField(blank=True, null=True)),
                ('stop_loss_pct', models.FloatField(blank=True, null=True)),
                ('trailing_stop_pct', models.FloatField(blank=True, null=True)),
                ('max_hold_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_daily_entries_per_symbol', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paper', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='OCC contract symbol, e.g. AAPL260605C00315000', max_length=32)),
                ('underlying_symbol', models.CharField(max_length=10)),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('strike_price', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(help_text='Number of contracts')),
                ('entry_price', models.FloatField(blank=True, help_text='Premium per share at entry', null=True)),
                ('exit_price', models.FloatField(blank=True, help_text='Premium per share at exit', null=True)),
                ('peak_price', models.FloatField(blank=True, null=True)),
                ('realized_pnl', models.FloatField(blank=True, help_text='Dollar P&L, already x100 for the contract multiplier', null=True)),
                ('alpaca_order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='albright_trading_app.optionstrategy')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='optionstrategy',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_option_strategy_name_per_user'),
        ),
    ]
