# Generated by Django 5.2.8 on 2026-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0012_optionstrategy_optiontrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategy',
            name='option_direction',
            field=models.CharField(choices=[('bidirectional', 'Bidirectional (buy signal → call, bearish signal → put)'), ('calls_only', 'Calls Only'), ('puts_only', 'Puts Only')], default='bidirectional', max_length=20),
        ),
    ]
