# Generated by Django 5.2.8 on 2026-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0014_strategy_market_regime_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategy',
            name='market_regime_filter',
            field=models.CharField(choices=[('none', 'No filter'), ('spy_bullish', 'Only when SPY is above its 50-day average'), ('spy_bearish', 'Only when SPY is below its 50-day average')], default='none', help_text="Only allow NEW entries (calls or puts) while this market condition holds. Doesn't affect exits.", max_length=20),
        ),
        migrations.AlterField(
            model_name='optionstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover'), ('reddit_sentiment_threshold', 'Reddit Sentiment Threshold'), ('rsi_threshold', 'RSI Threshold'), ('bollinger_reversion', 'Bollinger Band Reversion'), ('price_breakout', 'Price Breakout'), ('volume_spike', 'Volume Spike'), ('sector_relative_strength', 'Sector Relative Strength'), ('confluence', 'Confluence (Multiple Signals)')], max_length=50),
        ),
    ]
