# Generated by Django 5.2.8 on 2026-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0015_optionstrategy_market_regime_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSentimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('mentions_24h', models.PositiveIntegerField(default=0)),
                ('positive_24h', models.PositiveIntegerField(default=0)),
                ('neutral_24h', models.PositiveIntegerField(default=0)),
                ('negative_24h', models.PositiveIntegerField(default=0)),
                ('mentions_7d', models.PositiveIntegerField(default=0)),
                ('positive_7d', models.PositiveIntegerField(default=0)),
                ('neutral_7d', models.PositiveIntegerField(default=0)),
                ('negative_7d', models.PositiveIntegerField(default=0)),
                ('mentions_30d', models.PositiveIntegerField(default=0)),
                ('positive_30d', models.PositiveIntegerField(default=0)),
                ('neutral_30d', models.PositiveIntegerField(default=0)),
                ('negative_30d', models.PositiveIntegerField(default=0)),
                ('positive_change_24h_vs_7d_avg', models.FloatField(blank=True, null=True)),
                ('negative_change_24h_vs_7d_avg', models.FloatField(blank=True, null=True)),
                ('positive_change_7d_vs_30d_avg', models.FloatField(blank=True, null=True)),
                ('negative_change_7d_vs_30d_avg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-mentions_24h'],
            },
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='filter_min_news_mentions_24h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='filter_min_news_positive_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_news_mentions_24h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_news_positive_ratio',
            field=models.FloatField(blank=True, help_text='Positive news mentions as a fraction of all news mentions today.', null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover'), ('reddit_sentiment_threshold', 'Reddit Sentiment Threshold'), ('rsi_threshold', 'RSI Threshold'), ('bollinger_reversion', 'Bollinger Band Reversion'), ('price_breakout', 'Price Breakout'), ('volume_spike', 'Volume Spike'), ('sector_relative_strength', 'Sector Relative Strength'), ('confluence', 'Confluence (Multiple Signals)'), ('news_sentiment_threshold', 'News Sentiment Threshold')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover'), ('reddit_sentiment_threshold', 'Reddit Sentiment Threshold'), ('rsi_threshold', 'RSI Threshold'), ('bollinger_reversion', 'Bollinger Band Reversion'), ('price_breakout', 'Price Breakout'), ('volume_spike', 'Volume Spike'), ('sector_relative_strength', 'Sector Relative Strength'), ('confluence', 'Confluence (Multiple Signals)'), ('news_sentiment_threshold', 'News Sentiment Threshold')], max_length=50),
        ),
        migrations.CreateModel(
            name='NewsDailyMentionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='albright_tr_symbol_7f13e9_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='unique_news_symbol_per_day')],
            },
        ),
    ]
