# Generated by Django 5.2.8 on 2026-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albright_trading_app', '0016_newssentimentsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategy',
            name='filter_min_news_negative_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='filter_min_news_negative_vs_positive_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='filter_min_reddit_negative_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='filter_min_reddit_negative_vs_positive_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_news_negative_ratio',
            field=models.FloatField(blank=True, help_text='Negative news mentions as a fraction of all news mentions today. For sell/put entries.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_news_negative_vs_positive_ratio',
            field=models.FloatField(blank=True, help_text='Negative news mentions as a fraction of (positive + negative) only, neutral excluded. For sell/put entries.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_reddit_negative_ratio',
            field=models.FloatField(blank=True, help_text='Negative mentions as a fraction of ALL mentions today, including neutral. For sell/put entries.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_min_reddit_negative_vs_positive_ratio',
            field=models.FloatField(blank=True, help_text='Negative mentions as a fraction of (positive + negative) only. For sell/put entries.', null=True),
        ),
    ]
