# -----------------------------------------------------------------------------------------------------
"""
Django settings for Albright Trading Proj project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
TEMPLATE_DIR = os.path.join(BASE_DIR,"templates")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s%$41@b03e!rmoxdxnxctjw4y^u17skbo^0t$(c@mih6b*)r-+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["www.sportslabalgo.com",
                 "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'albright_trading_app',
    'albright_reselling_app',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'albright_trading_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'albright_trading_app.context_processors.current_app',
            ],
        },
    },
]

WSGI_APPLICATION = 'albright_trading_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': 'doadmin',
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        'HOST': 'db-pgsql-nyc3-98011-do-user-17268853-0.e.db.ondigitalocean.com',
        'PORT': '25060',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL ='/images/'

STATICFILES_DIRS = [
    BASE_DIR / "albright_trading_app" / "static",
]

# SMTP Configuration
'''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sportslabalgo@gmail.com'
EMAIL_HOST_PASSWORD = 'weqwxnrhunzrpbud'
'''

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Recaptcha Settings
'''
RECAPTCHA_PUBLIC_KEY = '6LeizuwqAAAAAMf9pXZk-sHoZVKJsxIZwd_ucQHw'
RECAPTCHA_PRIVATE_KEY = '6LeizuwqAAAAABI0EFSnLFrQuHBmfWYDgTvNo1to'
RECAPTCHA_DOMAIN = 'www.recaptcha.net'
'''

# Alpaca
ALPACA_API_KEY = os.environ.get("ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.environ.get("ALPACA_SECRET_KEY")
ALPACA_PAPER = True  # flip to False once you're trading live
ALPACA_CREDENTIALS_ENCRYPTION_KEY = "YjaZLd11-N65By3GD2MVt7w02yDM-IoFyH8OpDvlwkg="

# Reddit
REDDIT_CLIENT_ID = os.environ.get("REDDIT_CLIENT_ID")
REDDIT_CLIENT_SECRET = os.environ.get("REDDIT_CLIENT_SECRET")
REDDIT_USER_AGENT = "albright-trading-sentiment-bot/1.0 by u/sportslabalgo"

# For hosting on PythonAnywhere
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
ALLOWED_HOSTS = ["www.sportslabalgo.com", "127.0.0.1", "natealbright36.pythonanywhere.com"]

# OpenAI
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

# Reselling: Auction Scanner (coins & bullion) - see albright_reselling_app/scanner/
RESELLING_SCANNER = {
    "SOURCES": {
        "shopgoodwill": {
            "buyer_premium_pct": 0.0,        # verify on a ShopGoodwill invoice
            "sales_tax_pct": 0.07,           # use the rate on your actual invoice
            "default_inbound_shipping": 10.0,  # small-package estimate until we pull real quotes
            "timezone": "America/Los_Angeles",  # verify: compare one lot's end time vs the site
        },
        "maxsold": {
            "home_lat": 27.9000686, "home_lng": -82.5198206,   # Tampa - I'll replace with my home coordinates
            "radius_miles": 30,
            "buyer_premium_pct": 0.18,                  # PLACEHOLDER - verify on MaxSold
            "sales_tax_pct": 0.07,                      # PLACEHOLDER - verify on an invoice
            "default_inbound_shipping": 0.0,
            "mileage_rate": 0.70,                       # round trip, per mile
            "pickup_fixed_cost": 5.0,                   # my time per pickup trip
            "keywords": {"coins": ["silver coins", "gold coins", "coin collection", "old coins",
                                   "silver dollars", "silver bullion bars", "half dollars", "morgan dollar"],
                         "jewelry": ["14k gold", "10k gold", "18k gold", "gold jewelry lot",
                                     "sterling silver jewelry", "scrap gold", "gold chain", "gold ring"],
                         "games": ["nintendo 64", "gamecube", "game boy", "super nintendo", "nes games",
                                   "sega genesis", "video game lot", "playstation 2 games"],
                         "cards": ["pokemon cards", "baseball cards", "sports cards lot",
                                   "magic the gathering", "yugioh cards", "psa graded", "card binder",
                                   "trading card lot"]},
        },
    },
    "KEYWORDS": {
        "coins": ["morgan dollar", "peace dollar", "silver eagle", "90% silver", "junk silver",
                  "silver half dollar", "walking liberty", "franklin half", "kennedy half 1964",
                  "mercury dime", "silver quarter", "war nickel", "silver bar", "silver round",
                  "troy oz", "gold coin", "krugerrand"],
        "jewelry": ["14k gold", "10k gold", "18k gold", "gold jewelry lot", "sterling silver jewelry",
                    "scrap gold", "gold chain", "gold ring"],
        "games": ["nintendo 64", "gamecube", "game boy", "super nintendo", "nes games", "sega genesis",
                  "video game lot", "playstation 2 games"],
        "cards": ["pokemon cards", "baseball cards", "sports cards lot", "magic the gathering",
                  "yugioh cards", "psa graded", "card binder", "trading card lot"],
    },
    "FEES": {"ebay_fee_pct": 0.1325, "ebay_fixed_fee": 0.40, "outbound_shipping": 5.00,
             "packaging": 0.50, "min_profit": 10.00, "min_profit_pct": 0.20},
    "RESALE_MULTIPLIERS": {   # expected eBay sale as a multiple of melt; calibrate from your Ledger
        "default": 1.00, "junk_silver_face": 1.00, "silver_eagle": 1.08,
        "morgan_dollar": 1.00, "peace_dollar": 1.00,   # melt floor only; upside is flagged for you
        "generic_silver": 0.97, "generic_gold": 0.97,
        "jewelry_gold": 0.80, "jewelry_sterling": 0.60,
    },
    "CATEGORY_FEES": {
        "jewelry": {"ebay_fee_pct": 0.0, "ebay_fixed_fee": 0.0, "outbound_shipping": 0.0, "packaging": 0.0},
    },
    "LEAD_LIMITS": {"games": 40, "cards": 40, "jewelry": 60},
    "LEAD_WINDOW_HOURS": 48,
    "CANDIDATE_WINDOW_HOURS": 24,
    "CANDIDATE_CONFIDENCE": ["high", "medium"],
    "LLM": {"enabled": True, "model": "gpt-4o-mini", "max_calls_per_run": 25},
    "SPOT": {"monthly_api_limit": 90, "max_age_days": 3, "manual": {"silver": None, "gold": None}},
}